version: "3"
services:
  ask:
    container_name: "ask"
    build: .
    image: ask
    ports:
      - "8000:8000"
    volumes:
      - ./volume:/volume
    depends_on:
      - postgres

  postgres:
    container_name: "postgres"
    image: postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
