env: dev

dev:
  adapter: PostgreSQL
  database: postgres
  host: localhost
  username: postgres
  password: postgres
  port: 5432
  config:

prod:
  adapter: SQLite
  database: db/ask.sqlite
  host:
  username:
  password:
  port:
  config:

test:
  adapter: SQLite
  database:
  host:
  username:
  password:
  port:
  config: 
